/*
 * Programación y Diseño Orientado a Objetos - Práctica Qytetet
 * Enumerado OpcionMenu
 * Autor: Jose Luis Gallego Peña
 */
package controladorqytetet;

public enum OpcionMenu {
    INICIARJUEGO, 
    JUGAR, 
    APLICARSORPRESA, 
    INTENTARSALIRCARCELPAGANDOLIBERTAD,
    INTENTARSALIRCARCELTIRANDODADO, 
    COMPRARTITULOPROPIEDAD, 
    HIPOTECARPROPIEDAD,
    CANCELARHIPOTECA, 
    EDIFICARCASA, 
    EDIFICARHOTEL, 
    VENDERPROPIEDAD, 
    PASARTURNO,
    OBTENERRANKING, 
    TERMINARJUEGO, 
    MOSTRARJUGADORACTUAL, 
    MOSTRARJUGADORES,
    MOSTRARTABLERO
}
